config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms do
    collection do
      post :check_availability
    end
  end
  resources :bookings

  root :to => 'bookings#home'
  get 'home' => "bookings#home"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  enum room_type: { "Deluxe Rooms": 0, "Luxury Rooms": 1, "Luxury suites": 2, "Presidential Suites": 3 }

  belongs_to :room
  belongs_to :user

  before_validation :rooms_are_available
  before_create :add_room_total_cost

  validate :check_booking_date_range_between_six_months
  validates :user_id, :start_date, :last_date, presence: true
  validates_format_of :start_date, :last_date, :with => /\d{4}\-\d{2}\-\d{2}/, :message => "^Date must be in the following format: dd/mm/yyyy"


  def check_booking_date_range_between_six_months
    if dates_is_blank?
      errors.add(:start_date, "Please enter Check in date and Check out date")
    elsif Date.today > start_date.to_date
      errors.add(:start_date, "Check in date should be greater or equal to today's date")
    elsif Date.today + 6.months < start_date.to_date
      errors.add(:last_date, "Check in date should be smaller than 6 months")
    elsif Date.today + 6.months < last_date.to_date
      errors.add(:last_date, "Check out date should be smaller than 6 months")
    elsif last_date.to_date <= start_date.to_date
      errors.add(:last_date, "Check out date should be greater than Check in Date")
    end
  end

  # get the all the room_id which room are booked in between start_date and last_date
  def self.excluded_ids(start_date, last_date)
    existing_booking_ids = Booking.where("Date(start_date) < ? AND Date(last_date) > ? ", last_date, start_date).pluck(:room_id)
    if existing_booking_ids.blank?
      return false
    else
      return existing_booking_ids
    end
  end

  def rooms_are_available
    rooms = Room.available_rooms(start_date, last_date, room_type).limit(1)
    if rooms.length > 0
      self.room_id = rooms.first.id
    else
      errors.add(:number_of_person, "Rooms are not available #{room_type}")
    end
  end

  def dates_is_blank?
    if start_date.blank? || last_date.blank?
      return true
    end
  end

  def add_room_total_cost
    self.cost = (self.last_date - self.start_date).to_i * self.room.price
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  enum room_type: { "Deluxe Rooms": 0, "Luxury Rooms": 1, "Luxury suites": 2, "Presidential Suites": 3 }

  has_and_belongs_to_many :bookings

  def self.available_rooms(start_date, last_date, room_type = nil)
    if Booking.excluded_ids(start_date, last_date)
      self.where("room_type = ? AND id NOT IN (?)", Room.room_types[room_type], Booking.excluded_ids(start_date, last_date))
    else
      self.where("room_type = ?", Room.room_types[room_type])
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :rememberable
  # include DeviseTokenAuth::Concerns::User
  # validates :terms_of_service, acceptance: true
  validates :email, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { within: 6..12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy, :index, :show]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  # GET /bookings
  def index
    @bookings = current_user.bookings.includes(:room).paginate(page: params[:page], per_page: 10)
  end

  def home
    @booking = Booking.new
    @bookings = Booking.all
  end

  def show
    if @booking
      @room = @booking.room
    else
      redirect_to root_path
    end
  end

  # GET /bookings/new
  def new
    @booking = Booking.new(room_type: params[:room_type].to_i)
  end

  def create
    @booking = current_user.bookings.build(booking_params)
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
      else
        format.html { render :new}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = current_user.bookings.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params["booking"]["room_type"] = params["booking"]["room_type"].to_i if params["booking"]["room_type"].present?
      params.require(:booking).permit(:room_type, :room_id, :start_date, :last_date, :number_of_person, :cost)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :check_availability]
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
    @booking = Booking.new(room_type: @room.room_type)
  end

  def check_availability
    @errors = []
    if check_date_range(params[:check_in], params[:check_out])
      return false
    elsif params[:room_type].empty?
      @deluxe = Room.available_rooms(params[:check_in], params[:check_out], 'Deluxe Rooms').count
      @luxury_room = Room.available_rooms(params[:check_in], params[:check_out], 'Luxury Rooms').count
      @luxury_suite = Room.available_rooms(params[:check_in], params[:check_out], 'Luxury suites').count
      @presidential_suite = Room.available_rooms(params[:check_in], params[:check_out], 'Presidential Suites').count
    else
      @rooms = Room.available_rooms(params[:check_in], params[:check_out], params[:room_type]).count
    end
    respond_to do |format|
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:price, :room_no, :room_type)
  end

  def check_date_range(start_date, last_date)
    if Date.today > start_date.to_date
      @errors.push("check in date should be greater or equal to today's date")
    elsif Date.today + 6.months < start_date.to_date
      @errors.push("Check in date should be smaller than 6 months")
    elsif Date.today + 6.months < last_date.to_date
      @errors.push("Check out date should be smaller than 6 months")
    elsif last_date.to_date <= start_date.to_date
      @errors.push("Check out date should be greater than Check in Date")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      next unless message.is_a? String
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} alert-dismissable", style: "margin: 10px;") do
        concat content_tag(:button, 'x', class: "close", style: "font-size: 18px;", data: { dismiss: 'alert' })
        concat content_tag(:p, message)
      end)
    end
    nil
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    resource.errors.full_messages.each do |message|
      concat(content_tag(:div, message, class: "alert alert-danger alert-dismissable", style: "margin: 10px;") do
        concat content_tag(:button, 'x', class: "close", style: "font-size: 18px;", data: { dismiss: 'alert' })
        concat content_tag(:p, message)
      end)
    end
    nil
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_booking.html.erb
<div class = "booking">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class=" col-md-12 col-lg-12 ">
          <table class="table booking-information">
            <tbody>
              <tr>
                <th>Room No :</td>
                <td><%= @booking.room.room_no %></td>
              </tr>
              <tr>
                <th>Check In :</td>
                <td><%= @booking.start_date %></td>
              </tr>
              <tr>
                <th>Check Out :</td>
                <td><%= @booking.last_date %></td>
              </tr>
              <tr>
                <th>Room Type :</td>
                <td><%= @booking.room.room_type %></td>
              </tr>
              <tr>
                <th>Cost per room :</td>
                <td><%= @booking.room.price %></td>
              </tr>
              <tr>
                <th>Total Cost :</td>
                <td><%= @booking.cost %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<section class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <h2 class="mb-5">Reservation Form</h2>
          <%= form_for(@booking, html: { class: "room-booking", novalidate: 'novalidate' }) do |f| %>

          <% if @booking.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

              <ul>
                <% @booking.errors.messages.each do |attribute, message| %>
                  <li><%= message.first %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <label for="">Room Type</label>
            <div style="position: relative;">
              <%= f.select :room_type, options_for_select(Room.room_types, selected: params[:room_type]), {}, {class: 'form-control'} %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6 form-group">
              <label for=""><span style="color: red;">*</span> Check In Date</label>
              <div style="position: relative;">
                <%= f.date_field :start_date, class: "form-control", value: params[:start_date], required: 'required' %>
              </div>
            </div>

            <div class="col-sm-6 form-group">
              <label for=""><span style="color: red;">*</span> Check Out Date</label>
              <div style="position: relative;">
                <%= f.date_field :last_date, class: "form-control", value: params[:last_date], required: 'required' %>
              </div>
            </div>
          </div>

          <div class="row">


            <div class="col-md-6 form-group">
              <label for="room">Guests</label>
              <%= f.select :number_of_person, options_for_select([1, 2, 3, 4], 1), {}, {class: "form-control"} %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 form-group">
              <%= f.submit class: 'btn btn-default' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/bookings/_slider.html.erb
<div class="test" id="testimonials">
  <div class="container">
    <div class="test-top">
      <section class="slider">
        <div class="flexslider">
          <ul class="slides">
            <li>
              <div class="test-one">
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_0", size:"220x200", class: 'image-radius'), new_booking_path(room_type:0), class: 'image-radius' %>
                  <p class="flex-caption">Deluxe Rooms</p>
                  <h4>Deluxe Rooms - Queen Size Bed</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:0), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_1", size:"220x200", class: 'image-radius'), new_booking_path(room_type:1), class: 'image-radius' %>
                  <p class="flex-caption">Luxury Rooms</p>
                  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
                   <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_2", size:"220x200", class: 'image-radius'), new_booking_path(room_type:2), class: 'image-radius' %>
                  <p class="flex-caption">Luxury Suites</p>
                  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
                   <p><%= link_to 'Book Now', new_booking_path(room_type:2), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
            <li>
              <div class="test-one">
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_3", size:"220x200", class: 'image-radius'), new_booking_path(room_type:3), class: 'image-radius' %>
                  <p class="flex-caption">Presidential Suites</p>
                  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:3), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_0_1", size:"220x200", class: 'image-radius'), new_booking_path(room_type:0), class: 'image-radius' %>
                  <p class="flex-caption">Deluxe Rooms</p>
                  <h4>Deluxe Rooms - Queen Size Bed</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:0), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_1_1", size:"220x200", class: 'image-radius'), new_booking_path(room_type:1), class: 'image-radius' %>
                  <p class="flex-caption">Luxury Rooms</p>
                  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
            <li>
              <div class="test-one">
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_2_1", size:"220x200", class: 'image-radius'), new_booking_path(room_type:2) %>
                  <p class="flex-caption">Luxury Suites</p>
                  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:2), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_3_1", size:"220x200", class: 'image-radius'), new_booking_path(room_type:3) %>
                  <p class="flex-caption">Presidential Suites</p>
                  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:3), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_1", size:"220x200", class: 'image-radius'), new_booking_path(room_type:1) %>
                  <p class="flex-caption">Luxury Rooms</p>
                  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </div>
</div>
  <!--end-test-->

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/home.html.erb
<body>
  <!--start-header-->
  <section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url(assets/big_image_1.jpg);">
  <div class="container">
    <div class="row align-items-center site-hero-inner justify-content-center">
      <div class="col-md-12 text-center">

        <div class="mb-5">
          <h1>Homewood Suites. Make Yourself at Home.</h1>
          <p>Connect with the second life here.</p>
          <br>
          <p> Hotels with personality.</p>
          <br>
          <p> Your best bet is a NeoHotel.</p>
          <br>
          <p><%= link_to 'Book Now', new_booking_path, class: 'btn btn-primary'  %></p>
        </div>

      </div>
    </div>
  </div>
</section>

  <!-- <div class="banner">
    <div class="container">
      <div class="banner-top">
        <%#= render "form"%>
      </div>
    </div>
  </div> -->
  <%= render "slider" %>
</body>

app/views/bookings/index.html.erb
<div id="wrap">
  <div id="main" class="container clear-top">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Room No</th>
          <th>Start Date</th>
          <th>Last Date</th>
          <th>Guest</th>
          <th> Show <th>
        </tr>
      </thead>
      <% @bookings.each do |booking|%>
        <tr>
          <td><%= booking.user.email %></td>
          <td><%= link_to booking.room.room_no, booking %> </td>
          <td><%= booking.start_date %></td>
          <td><%= booking.last_date %></td>
          <td><%= booking.number_of_person %></td>
          <td> <%= link_to "Show", booking %> </td>
        </tr>  
      <%end%>
    </table>
    <%= will_paginate @bookings %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="services">
  <div class="container">
    <div class="col-md-6 services-left">
      <%= render "rooms/room_#{params['room_type'].to_i}"%>
    </div>
    <div class="col-md-6 services-right" style = "background-color: #4b4f50;">
      <%= render "bookings/form"%>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="services">
  <div class="container">
    <div class="col-md-12 services-right">
      <h3> Booking Detail</h3>
        <%= render "booking"%>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="black-wrapper">
  <div class="subfooter">
    <div class="container">
      <div class="pull-left">
        <h4>NeoHotel</h1>
        <p class="pull-left">www.neoHotel.hotel.com</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_top_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">NeoHotel</a>
    </div>
    <nav class="navigation row" id = "navigation_bar" style="float: right; margin-right: 50px;">
      <span class="menu"></span>
      <ul class="nav navbar-nav" style="font-size: 20px !important">
        <li><a href="/rooms" class="hvr-bounce-to-bottom fa fa-bed"> Rooms</a></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Bookings', bookings_path, class: "hvr-bounce-to-bottom fa fa-book" %></li>
          <li>
            <a class="hvr-bounce-to-bottom" ><%= current_user.email %></a>
          </li>
          <li><%= link_to 'Log out', destroy_user_session_path, class: "hvr-bounce-to-bottom fa fa-sign-out", method: :delete %></li>

          </li>
        <% else %>
           <li><a href="/users/sign_up" class="hvr-bounce-to-bottom fa fa-user-plus"> Sign Up</a></li>
           <li><a href="/users/sign_in" class="hvr-bounce-to-bottom fa fa-sign-in"> Login</a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotelRoomBooking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag("application") %>
  <%= javascript_include_tag("jquery.flexslider")%>
  <%= csrf_meta_tags %>

  <title>Paix a Hotel Category Flat Bootstarp responsive Website Template | Home :: w3layouts</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <!---- start-smoth-scrolling---->

  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $(".scroll").click(function(event){   
        event.preventDefault();
        $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
      });
    });
  </script>
  <!--start-smoth-scrolling-->
</head>
<body class="black-bg">
    <%= render "layouts/top_navbar" %>
    <div class="container">
      <div class="wrapper">
        <div class="row"><%= flash_messages %></div>
        <%= yield %>
      </div>
    </div>
    <%= render "layouts/footer"%>
</body>
</html>

app/views/rooms/_available_rooms.html.erb
<% if @errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @errors.each do | message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% elsif params[:room_type].blank? %>
  <table class="col-sm-12 ">
    <thead>
      <tr>
        <th>Room Type</th>
        <th>Available Rooms</th>
        <th>Book now</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>Deluxe Rooms</td>
        <td><%= @deluxe %></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type: 0, start_date: params[:check_in], last_date: params[:check_out]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
      <tr>
        <th>Luxury Rooms</td>
        <td><%= @luxury_room %></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type: 1, start_date: params[:check_in], last_date: params[:check_out]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
      <tr>
        <th>Luxury suites</td>
        <td><%= @luxury_suite %></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type: 2, start_date: params[:check_in], last_date: params[:check_out]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
      <tr>
        <th>Presidential Suites</td>
        <td><%= @presidential_suite %></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type: 3, start_date: params[:check_in], last_date: params[:check_out]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
    </tbody>
  </table>
<% else %>
  <table class="col-sm-12 ">
    <thead>
      <tr>
        <th>Room Type</th>
        <th>Available Rooms</th>
        <th>Book now</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= params[:room_type]%></td>
        <td><%= @rooms %></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type: Room.room_types[params[:room_type]], start_date: params[:check_in], last_date: params[:check_out]), class: 'btn btn-primary btn-sm'%></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :room_no %><br>
    <%= f.number_field :room_no %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.number_field :room_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room_0.html.erb
<div class="services-one border">
  <div class="flexslider flexslider-padding">
    <div>
      <%= link_to image_tag("room_0", class: "img-responsive",height: 300, width: 450), new_booking_path(room_type: 0) %>
    </div>
    <div class="clearfix"></div>
  </div>

  <h4>Deluxe Rooms - Queen Size Bed</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>Queen Size Bed</li>
    <li>Beautifu Views</li>
    <li>7000 per night</li>
  </ul>
  <% if current_page?(rooms_path) %>
    <p><%= link_to 'Book Now', new_booking_path(room_type:0), class: 'btn btn-primary'  %></p>
  <% end %>
</div>

app/views/rooms/_room_1.html.erb
<div class="services-one">
  <section class="slider">
    <div class="flexslider flexslider-padding">
      <div>
        <%= link_to image_tag("room_1", class: "img-responsive", height: 300, width: 450), new_booking_path(room_type: 1) %>
      </div>
      <div class="clearfix"></div>
    </div>
  </section>
  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>Queen Size Bed</li>
    <li>Swimming Pool</li>
    <li>8500 per night</li>
  </ul>
  <% if current_page?(rooms_path) %>
    <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary'  %></p>
  <% end %>
</div>

app/views/rooms/_room_2.html.erb
<div class="services-one">
  <div class="flexslider flexslider-padding">
    <div>
      <%= link_to image_tag("room_2",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type: 2) %>
    </div>
    <div class="clearfix"></div>
  </div>
  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>King Size Bed</li>
    <li>Swimming Pool</li>
    <li>12000 per Night</li>
  </ul>
  <% if current_page?(rooms_path) %>
    <p><%= link_to 'Book Now', new_booking_path(room_type:2), class: 'btn btn-primary'  %></p>
  <% end %>
</div>

app/views/rooms/_room_3.html.erb
<div class="services-one">
  <section class="slider">
    <div class="flexslider flexslider-padding">
      <div>
        <%= link_to image_tag("room_3",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type: 3) %>
      </div>
      <div class="clearfix"></div>
    </div>
  </section>
  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>King Size Bed</li>
    <li>Swimming Pool</li>
    <li>20000 per night</li>
  </ul>
  <% if current_page?(rooms_path) %>
    <p><%= link_to 'Book Now', new_booking_path(room_type:3), class: 'btn btn-primary'  %></p>
  <% end %>
  <div class="clearfix"></div>
</div>

app/views/rooms/check_availability.js.erb
$("#available").html("<%= j render(partial: 'available_rooms') %>");